
# Loads default set of integrations. Do not remove.
default_config:
lovelace:
  mode: yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: vasttrafik
    departures:
      - from: Brunnsparken
        heading: Chalmers
      - from: Angered


# views:
#   - title: My Map View
#     icon: mdi:map
#     cards:
#       - type: map
#         entities:
#           - sensor.vasttrafik