# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

sensor:
  - platform: vasttrafik
    departures:
      - from: Brunnsparken
        heading: Grönsakstorget
      - from: Styrsö Bratten
        heading: Bifrost